from register import *
from login import *
from tambah_game import *
from ubah_game import *
from ubah_stok import *
from list_game_toko import *
from buy_game import *
from list_game import *
from search_my_game import *
from search_game_at_store import *
from topup import *
from riwayat import *
from help import *
from load import *
from save import *
from exit import *
from info import *
from kerangajaib import *
from tictactoe import *